language: cpp
dist: trusty
compiler: gcc
os: linux

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - boost1.68

berfore_script:
  - mkdir build
  - cd build

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake --version
  - cmake ..
  - cmake  --build . 